embeddings:
  path: sentence-transformers/all-MiniLM-L6-v2

api:
  host: 0.0.0.0
  port: 8000
writable: true
# Run the following from project root in its own terminal tab
# docker run --rm -p 8001:8000 \
#   -e CONFIG=/app/app.yml \
#   -v "$PWD/semantic_search_service/app.yml:/app/app.yml" \
#   neuml/txtai
